### PR TITLE
Configurable Proxy Listening Port

### LINKED ISSUE #1: Add ability to configure proxy listening port
Users should have the ability to configure the listening port either by using the `config.yml` file or via environment variable

### PR DESCRIPTION
**Pull request by everythingguy**
Resolves #1

### CODE REVIEW

**Comment by dapor2000** [comment]
Please someone merge this.
With the default config the container is unusable with unRAID Server

**Review by ItsEcholot — CHANGES_REQUESTED** [review]
The actual listening port isn’t changed by this PR.
Additionally the port config won’t be reloaded on config file save like the rest of the config… Maybe it makes more sense to implement this using a simple `env` var? Or do we want to support changing the port after a config reload?

**Comment by ItsEcholot** [comment]
@dapor2000 
> With the default config the container is unusable with unRAID Server

It is usable. Either a) run the container with bridge networking and change the port mapping to whatever port you want or b) change the unraid webui port.

Option a is easier and much better in general.

**Comment by dapor2000** [comment]
> It is usable. Either a) run the container with bridge networking and change the port mapping to whatever port you want 

sorry my mind went blank 

Sure its no problem

**Comment by everythingguy** [comment]
@ItsEcholot I am confused on what you mean by "The actual listening port isn’t changed by this PR". Are you referring to the placeholderServerListeningPort?

**Comment by ItsEcholot** [comment]
Ah my fault I misread the code. But the point about it not reloading the settings still stands.

**Comment by everythingguy** [comment]
I have implemented the live reload for the proxy port. Would it be better to use an event emitter instead of the updateProxyServer function?

**Comment by ItsEcholot** [comment]
I like the #14 approach better, thanks for providing an alternative.

**Pull request closed without merging**
